app_parking/app_accounts/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from django.urls import path


from . import views


app_name = "app_accounts"


urlpatterns = [
    path("register_form/", views.sign_up_user, name="register_form"),
    path("login/", views.login_user, name="login"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("logout/", views.logout_user, name="logout"),
    path("edit_profile/<str:username>/", views.edit_profile, name="edit_profile"),
    path("parking-history/", views.parking_history, name="parking_history"),
    path("parking/", views.parking_view, name="parking"),
    path("top_up_balance/", views.top_up_balance, name="top_up_balance"),
    path("pay_parking/<int:record_id>/", views.pay_parking, name="pay_parking"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path("reset-password/done/", PasswordResetDoneView.as_view(template_name="app_accounts/password_reset_done.html"),
         name="password_reset_done"),
    path("reset-password/confirm/<uidb64>/<token>/",
         PasswordResetConfirmView.as_view(template_name="app_accounts/password_reset_confirm.html",
                                          success_url=reverse_lazy("app_accounts:password_reset_complete")),
         name="password_reset_confirm"),
    path("reset-password/complete/",
         PasswordResetCompleteView.as_view(template_name="app_accounts/password_reset_complete.html"),
         name="password_reset_complete"),
]

app_parking/app_home/urls.py
from django.urls import path,include
from . import views


app_name = 'app_home'

urlpatterns = [
    path('', views.home, name='home'),
    #path('profile/', views.profile, name='profile'),
    path('registration/', views.registration, name='registration'),
    path('edit-profile/', views.edit_profile, name='edit_profile')
]

app_parking/app_parking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_home.urls")),
    path("", include("app_accounts.urls")),
    path("", include("app_car_moderation.urls")),
    path('', include('app_photo.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_parking/app_photo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'app_photo'

urlpatterns = [
    path('profile/', views.upload, name='upload'),
    path('profile_avatar/', views.upload_avatar, name='upload_avatar')
]

app_parking/app_accounts/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models

def default_avatar():
    return 'app_accounts/images/default_avatar.jpg'

class User(AbstractUser):
    RATE_CHOICES = [
        ("basic", "Basic"),
        ("premium", "Premium"),
        ("standard", "Standard"),
    ]
    profile_image = models.ImageField(upload_to='profile_images/', default=default_avatar)
    email = models.EmailField(unique=True)
    role = models.CharField(
        max_length=10, choices=[("admin", "Admin"), ("user", "User")], default="user"
    )
    is_active = models.BooleanField(default=True)
    full_name = models.CharField(max_length=60)
    phone_number = models.CharField(max_length=15)
    address = models.CharField(max_length=255, blank=True, null=True)
    money_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    created_at = models.DateTimeField(auto_now_add=True)
    birth_date = models.DateField(null=True, blank=True)
    # bio = models.CharField(max_length=500)

    # Custom related_name settings to avoid conflicts
    groups = models.ManyToManyField(
        Group,
        related_name="custom_user_set",
        blank=True,
    )


    user_permissions = models.ManyToManyField(
        Permission,
        related_name="custom_user_set",
        blank=True,
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    avatar = models.FileField(upload_to='photo_for_users', max_length=500,null=True)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    
    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

    
class ParkingHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.full_name} - {self.location} - {self.date}"
    

app_parking/app_accounts/views.py
from django.contrib.auth import (
    authenticate,
    login,
    logout,
    get_user_model,
    get_backends,
)
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.views import View
from django.core.exceptions import ObjectDoesNotExist

from .forms import (
    SignUpForm,
    LoginForm,
    UserChangeForm,
    UserProfileForm,
    PasswordChangeForm,
)
from .forms import BalanceTopUpForm
from app_car_moderation.models import CarList, ParkingRecord, Payment, Rate
from app_photo.models import Car_Image
from django.contrib import messages
from decimal import Decimal
from django.utils import timezone
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from django.utils.dateparse import parse_datetime
from django.urls import reverse

from .models import Profile
from app_car_moderation.models import ParkingRecord
from urllib.parse import unquote
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
User = get_user_model()


def sign_up_user(request):
    if request.user.is_authenticated:
        return redirect(to="app_home:index")

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            backend = get_backends()[0]
            user.backend = f"{backend.__module__}.{backend.__class__.__name__}"
            login(request, user, backend=user.backend)

            username = user.username
            messages.success(
                request,
                f"Welcome, {username}!<br>Registration successful! Redirecting to your profile...",
            )

            return render(
                request,
                "app_accounts/register_form.html",
                context={
                    "form": form,
                    "redirect": True,
                    "redirect_url": reverse(
                        "app_accounts:profile", kwargs={"username": username}
                    ),
                },
            )

        else:
            messages.error(
                request, "There was an error with your registration. Please try again."
            )
            return render(
                request, "app_accounts/register_form.html", context={"form": form}
            )
    else:
        form = SignUpForm()
    return render(request, "app_accounts/register_form.html", context={"form": form})


def login_user(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        if email and password:
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                return redirect("app_accounts:profile", username=user.username)
            else:
                messages.error(request, "Invalid email or password.")
                return redirect("app_accounts:login")
        else:
            form = LoginForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data.get("username")
                password = form.cleaned_data.get("password")
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect("app_accounts:profile", username=username)
                else:
                    messages.error(request, "Invalid username or password.")
            else:
                messages.error(request, "Please enter both username and password.")
    else:
        form = LoginForm()

    return render(request, "app_accounts/login.html", {"form": form})


def format_duration(duration):
    total_seconds = int(duration.total_seconds())
    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    seconds = total_seconds % 60
    return f"{hours}h {minutes}m {seconds}s"

from urllib.parse import unquote

@login_required
def profile(request, username):

    user = get_object_or_404(User, username=username)
    user_profile_avatar = get_object_or_404(Profile, user=user)


    if user != request.user:
        return redirect("app_accounts:profile", username=request.user.username)


    last_parking_session = (
        ParkingRecord.objects.filter(user=user, exit_time__isnull=False)
        .order_by('-exit_time')
        .first()
    )
    last_parking_text = last_parking_session.exit_time.strftime('%Y-%m-%d %H:%M:%S') if last_parking_session else "No recent activity."


    membership_since = user.date_joined.strftime('%B %Y')
    total_parkings = ParkingRecord.objects.filter(user=user).count()


    current_parking = ParkingRecord.objects.filter(user=user, is_parked=True).first()
    current_parking_info = None
    parked_car_photo_url = None

    if current_parking:

        duration = timezone.now() - current_parking.entry_time
        formatted_duration = format_duration(duration)

        current_parking_info = {
            'license_number': current_parking.license_number,
            'rate_name': current_parking.rate.rate_name if current_parking.rate else "Unknown",
            'entry_time': current_parking.entry_time.strftime('%Y-%m-%d %H:%M:%S'),
            'hours_parked': formatted_duration,
            'status': "On Parking",
        }

        parked_car_photo = Car_Image.objects.filter(
            number_car=current_parking.license_number, user=user
        ).order_by('-detected_at').first()


        if parked_car_photo and parked_car_photo.image:
            image_url = parked_car_photo.image.url
            

            fixed_url = unquote(image_url)


            if fixed_url.startswith('/https:'):
                fixed_url = fixed_url[1:] 
            
            parked_car_photo_url = fixed_url
            print(f"Окончательно исправленный URL: {parked_car_photo_url}")


    context = {
        "user": user,
        "user_profile_avatar": user_profile_avatar,
        "parking_records": ParkingRecord.objects.filter(user=user),
        "latest_record": current_parking_info,
        'last_parking_text': last_parking_text,
        'membership_since': membership_since,
        'total_parkings': total_parkings,
        'parked_car_photo_url': parked_car_photo_url,  
    }

    return render(request, "app_accounts/profile.html", context)

@login_required
def logout_user(request):
    logout(request)
    return redirect("app_home:index")


@login_required
def edit_profile(request, username):
    user = get_object_or_404(User, username=username)
    user_profile_avatar = get_object_or_404(Profile, user=user)

    active_tab = request.GET.get("tab", "account-general")

    form = UserProfileForm(instance=request.user)
    password_form = PasswordChangeForm(user=request.user)

    if request.method == "POST":
        if "save_profile" in request.POST:
            form = UserProfileForm(request.POST, request.FILES, instance=request.user)
            if form.is_valid():
                print("Form is valid. Saving data...")
                form.save()
                messages.success(
                    request, "Profile updated successfully.", extra_tags="edit_profile"
                )
                return redirect("app_accounts:profile", username=request.user.username)
            else:
                print("Form is not valid:", form.errors)
                messages.error(
                    request,
                    "Please correct the errors below.",
                    extra_tags="edit_profile",
                )
            active_tab = "account-general"

        elif "change_password" in request.POST:
            password_form = PasswordChangeForm(user=request.user, data=request.POST)
            if password_form.is_valid():
                user = password_form.save()
                update_session_auth_hash(request, user)
                messages.success(
                    request,
                    "Your password was successfully changed.",
                    extra_tags="edit_profile",
                )
                return redirect(
                    "app_accounts:edit_profile", username=request.user.username
                )
            else:
                messages.error(
                    request,
                    "Please correct the errors below.",
                    extra_tags="edit_profile",
                )
            active_tab = "account-change-password"

    return render(
        request,
        "app_accounts/edit_profile.html",
        {
            "form": form,
            "password_form": password_form,
            "user_profile_avatar": user_profile_avatar,
            "active_tab": active_tab,
        },
    )


@login_required
def profile_view(request):
    if request.method == "POST":
        form = BalanceTopUpForm(request.POST)
        if form.is_valid():
            amount = form.cleaned_data["amount"]
            request.user.profile.balance += amount
            request.user.profile.save()
            return redirect("app_accounts:profile")

    else:
        form = BalanceTopUpForm()

    return render(request, "app_accounts/profile.html", {"form": form})


@login_required
def top_up_balance(request):
    if request.method == "POST":
        amount = request.POST.get("amount")
        if amount:
            try:
                amount = Decimal(amount)
                print(amount)

                if amount > 0:
                    request.user.money_balance += amount
                    request.user.save()
                    messages.success(
                        request,
                        f"Your balance has been topped up by ${amount:.2f}.",

app_parking/app_accounts/templates/app_accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log In</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap">
    {% load static %}
    <link rel="icon" href="{% static 'app_accounts/images/icons/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'app_accounts/css/login.css' %}">
    <script src="{% static 'app_accounts/js/login.js' %}" defer></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
</head>

<body>
    <a class="navbar-brand" href="/">
        <span class="brand-text">
            WEB_WORLD: PARK-AUTO
        </span>
    </a>
    <div class="bg-box">
        <img src="{% static 'slider-bg.jpg' %}" alt="">
    </div>
    <div class="wrapper">
        <div class="form-container">
            <h2>Log In</h2>
            <a href="/" class="close-btn" id="close-btn">&times;</a>

            <p class="agreement-text" id="agreement-text">
                By continuing, you agree to our <a href="#">User Agreement</a> and acknowledge that you understand the <a href="#">Privacy Policy</a>.
            </p>
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <form method="post" id="loginForm">
                {% csrf_token %}

                <div class="input-group">
                    <label for="identifier" class="required">Email or login</label>
                    <input type="text" name="email" class="form-control" id="id_email" placeholder="Email or login" required />
                    <span class="icon"><ion-icon name="person-sharp"></ion-icon></span>
                </div>
                <div class="input-group">
                    <label for="password" class="required">Password</label>
                    <input type="password" name="password" class="form-control" id="id_password" placeholder="Password" required />
                    <span class="icon"><ion-icon name="key-sharp"></ion-icon></span>
                    <!-- Иконка для отображения пароля -->
                    <span class="toggle-password">
                        <ion-icon name="eye-off-sharp" id="toggle-password-icon"></ion-icon>
                    </span>
                </div>

                <div class="button-wrapper">
                    <button type="submit" class="button disabled-button" disabled>Log In</button>
                </div>
            </form>
            <div class="forgot-password-link">
                <a href="{% url 'app_accounts:password_reset' %}" id="forgot-password-link">Forgot password?</a>
            </div>
            <div class="signup-redirect">
                <p>New to W.W: Park-auto? <a href="{% url 'app_accounts:register_form' %}" id="signup-link">Sign Up</a></p>
            </div>
        </div>
    </div>
</body>
</html>

app_parking/app_accounts/templates/app_accounts/parking.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Parking Now</title>
    {% load static %}
    <link rel="icon" href="{% static 'app_accounts/images/icons/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'app_accounts/css/parking.css' %}">
    <script src="{% static 'app_accounts/js/parking.js' %}" defer></script>
</head>
<body>
    <div class="bg-box">
        <img src="{% static 'slider-bg.jpg' %}" alt="Background Image">
    </div>
    <div class="navbar">
        <a class="navbar-brand" href="/">
            WEB_WORLD: PARK-AUTO
        </a>
    </div>

    <div class="parking-container">
        {% if messages %}
            {% for message in messages %}
                {% if 'if_parking' in message.tags %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        <section class="photo-upload">
            <h2>Car parking</h2>
            <form method="POST" enctype="multipart/form-data" action="{% url 'app_photo:upload' %}">
                {% csrf_token %}
                {% if form.errors %}
                    <div class="alert alert-danger">
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                <div id="uploaded-car-photos" class="uploaded-photos-container">
                    {% if car_photos %}
                        {% for photo in car_photos %}
                            <img src="{{ photo.image }}" alt="Car photo" class="uploaded-car-photo">
                        {% endfor %}
                    {% else %}
                        <p>There are no uploaded photos.</p>
                    {% endif %}
                </div>

                <div class="custom-file-upload">
                    <label for="car-photo-upload" class="custom-file-label">Park the car</label>
                    <input type="file" id="car-photo-upload" name="image" accept="image/*" class="custom-file-input">
                </div>
                <div class="button-container">
                    <button type="submit" class="upload-button" disabled>Save</button>
                    <button type="button" class="cancel-button" onclick="window.location.reload();">Cancel</button>
                </div>
                <div class="back-to-profile-container">              
                    <a href="{% url 'app_accounts:profile' username=user.username %}" class="back-to-profile">Back to Profile</a>
                </div>

                <div class="pricing-options">
                    <p>Select a Parking Rate:</p>
                    {% for rate in rates %}
                        <label>
                            <input type="radio" name="rate" value="{{ rate.id }}">
                            {{ rate.rate_name }} - ${{ rate.rate_per_hour }}
                        </label>
                    {% endfor %}
                </div>

            </form>      
        </section>
    </div>
</body>
</html>

app_parking/app_accounts/templates/app_accounts/password_reset.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password reset</title>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    {% load static %}
    <link rel="icon" href="{% static 'app_accounts/images/icons/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'app_accounts/css/password_reset.css' %}">
    <script src="{% static 'app_accounts/js/password_reset.js' %}" defer></script>
</head>
<body>
    <div class="bg-box">
        <img src="{% static 'slider-bg.jpg' %}" alt="Background Image">
    </div>
    <div class="navbar">
        <a class="navbar-brand" href="/">
            WEB_WORLD: PARK-AUTO
        </a>
    </div>
    <div class="wrapper">
        <div class="form-container">
            <a href="{% url 'app_accounts:login' %}" class="back-arrow">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M15 8a.5.5 0 0 1-.5.5H2.707l3.147 3.146a.5.5 0 0 1-.708.708l-4-4a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 7.5H14.5A.5.5 0 0 1 15 8z"/>
                </svg>
            </a>
            <h2 class="text-center">Reset your password</h2>
            <a href="/" class="close-btn" id="close-btn">&times;</a>
            <p class="agreement-text" id="agreement-text">
                Enter your email address or username and we’ll send you a link to reset your password
            </p>
            <form method="post" class="needs-validation" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_email">Email or login<span class="required">*</span></label></label>
                    <input type="email" class="form-control" id="id_email" name="email" placeholder="Email or login" required/>
                    <span class="icon"><ion-icon name="mail-sharp"></ion-icon></span>
                    <div class="invalid-feedback">
                        Please provide a valid email.
                    </div>
                </div>
                <div class="pass-submit"> 
                    <button type="submit" class="btn btn-success disabled-button" disabled>Reset password</button>
                </div>
            </form>
            <div class="need_help" id="need_help">
                <a href="#" id="need_help">Need help?</a>
            </div>
        </div>
    </div>
</body>
</html>

app_parking/app_accounts/templates/app_accounts/password_reset_email.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password reset email</title>
    {% load static %}
    <link rel="icon" href="{% static 'app_accounts/images/icons/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'app_accounts/css/password_reset_email.css' %}">
</head>
<body>
    {% autoescape off %}
    <body>
    <div class="bg-box">
        <img src="{% static 'slider-bg.jpg' %}" alt="Background Image">
    </div>
    <div class="navbar">
        <a class="navbar-brand" href="/">
            WEB_WORLD: PARK-AUTO
        </a>
    </div>
    <p>Hi {{ user.username }},</p>
    <p>You requested a password reset for your account. Please follow this link to set a new password:</p>
    <p>
        <a href="{{ protocol }}://{{ domain }}{% url 'app_accounts:password_reset_confirm' uidb64=uid token=token %}">
            {{ protocol }}://{{ domain }}{% url 'app_accounts:password_reset_confirm' uidb64=uid token=token %}
        </a>
    </p>
    <p>If you didn't request a password reset, please ignore this email.</p>
    <p>Thanks,</p>
    <p>The Our Team</p>
    {% endautoescape %}
</body>
</html>

app_parking/app_accounts/templates/app_accounts/profile.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap">
    {% load static %}
    <link rel="icon" href="{% static 'app_accounts/images/icons/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'app_accounts/css/profile.css' %}">
    <script src="{% static 'app_accounts/js/profile.js' %}" defer></script>
</head>
<body>
    <div class="bg-box">
        <img src="{% static 'slider-bg.jpg' %}" alt="">
    </div>
    <div class="navbar">
        <a class="navbar-brand" href="/">
            WEB_WORLD: PARK-AUTO
        </a>
        <div class="profile-actions">
            <a class="btn" href="{% url 'app_accounts:parking_history' %}">History of Parking</a>
            <a class="btn" href="{% url 'app_accounts:parking' %}">Parking Now</a>
            <a class="btn" href="{% url 'app_accounts:edit_profile' user.username %}">Edit Profile</a>
            <a class="btn" href="{% url 'app_home:index' %}">Back to Main</a>
            <a class="btn" href="{% url 'app_accounts:logout' %}">Logout</a>
        </div>
    </div>

    <div class="profile-container">
        <header class="profile-header">
            <div class="avatar-section">
                <div class="avatar-wrapper">
                    {% if user_profile_avatar.avatar %}
                        <img id="avatar" src="{{ user_profile_avatar.avatar }}" alt="User avatar">
                    {% else %}
                        <img id="avatar" src="{% static 'app_accounts/images/default_avatar.jpg' %}" alt="Default avatar">
                    {% endif %}
                </div>
            </div>

            <div class="user-details">
                <h1 id="username">{{ user.full_name }}</h1>
                <div class="status-container">
                    <span class="status-text">Status:</span>
                    <span class="status-icon online-status"></span>
                    <span class="status-label">Online</span>
                </div>
                <p>Email: {{ user.email }}</p>
                <p>Phone: {{ user.phone_number }}</p>
                <p>Address: {{ user.address }}</p>
                <p>Balance: ${{ user.money_balance }}</p> 
                <button class="btn-top-up" onclick="toggleTopUpForm()">Top Up Balance</button>


                <div id="balance-top-up-form" class="top-up-form">
                    <form method="POST" action="{% url 'app_accounts:top_up_balance' %}">
                        {% csrf_token %}
                        <input type="number" name="amount" placeholder="Enter amount" min="1" required class="top-up-input">
                        <div class="form-buttons">
                            <button type="submit" class="btn-submit">Submit</button>
                            <button type="button" class="btn-cancel" onclick="toggleTopUpForm()">Cancel</button>
                        </div>
                    </form>
                </div>
            </div>
        </header>
    
        <section class="additional-info">
            <h2>About Me</h2>
            <p>{{ user_profile.about_me|default:"No information provided." }}</p>

            <h2>Recent Activity</h2>
            <ul>
                <li>Last parking session: {{ last_parking_text }}</li>
                <li>Membership since: {{ membership_since }}</li>
                <li>Total parkings: {{ total_parkings }}</li>
            </ul>
        </section>
        <section class="current-parking">
            <h2>Current Parking</h2>
            {% if latest_record %}
                <ul>
                    <li>Status: <span class="status-dot"></span> {{ latest_record.status }}</li>
                    <li>License Number: {{ latest_record.license_number }}</li>
                    <li>Rate: {{ latest_record.rate_name }}</li>
                    <li>Parked Since: {{ latest_record.entry_time }}</li>
                    <li>Duration: {{ latest_record.hours_parked }} hours</li>
                </ul>
                {% if parked_car_photo_url %}
                    <img src="{{ parked_car_photo_url }}" alt="Parked Car Image" class="parked-car-photo">
                {% else %}
                    <p>No photo available for the parked car.</p>
                {% endif %}
            {% else %}
                <p>No cars currently parked.</p>
            {% endif %}
        </section>
    </div>
</body>
</html>